// Code generated by `mygo generate`. DO NOT EDIT.

import { call, type Channel } from "mygo-runtime";

// ---- Types ----

/** Config is everything the hub persists. */
export interface Config {
  /**
   * StorePath is the project directory skills are installed into with
   * `npx skills add`; the hub distributes them from there.
   */
  storePath: string;
  sources: LocalSource[];
  targets: Target[];
  /** Groups overrides the group a skill is listed under, by skill name. */
  groups: Record<string, string>;
  /** Triggers holds the user's manual/auto choice per skill name. */
  triggers: Record<string, TriggerOverride>;
}

/** Installed describes one skill directory found in a target. */
export interface Installed {
  name: string;
  /**
   * State is how the entry relates to the hub's skill of that name:
   *   linked    a symlink to the hub's skill, always current
   *   synced    a copy with the same contents
   *   outdated  a copy that differs, or one missing from an enabled directory
   *   conflict  the name is a hub skill's, but the entry links elsewhere
   *   foreign   the hub has no skill of that name
   */
  state: string;
  /**
   * Agents and Claude tell what sits in each skills directory: "",
   * "link", "copy", or "alias" for .claude's relative link to .agents.
   */
  agents: string;
  claude: string;
  /** LinkTo is where a symlink points. */
  linkTo: string;
  /**
   * Trigger is "auto", "manual" or "mixed", read from the installed
   * files: whether agents may load the skill on their own (see trigger.go).
   */
  trigger: string;
}

/** LocalSource is a folder of the user's own skills that the hub reads in place. */
export interface LocalSource {
  id: string;
  path: string;
}

/** Skill is one skill the hub can distribute. */
export interface Skill {
  name: string;
  description: string;
  /** Path is the skill's directory, the one holding SKILL.md. */
  path: string;
  /**
   * Origin is "store" for skills installed into the store and "local"
   * for those of a linked folder.
   */
  origin: string;
  /**
   * Source is the package the skill came from (store) or the linked
   * folder (local).
   */
  source: string;
  group: string;
  /** Hash identifies the skill's contents; see hashDir. */
  hash: string;
  /**
   * Conflict marks a skill whose name is taken by an earlier one. It
   * cannot be installed, since targets hold one directory per name.
   */
  conflict: boolean;
  /**
   * Claude and Codex are "auto" or "manual": whether that agent may load
   * the skill on its own. Trigger sums them up, "mixed" when they differ.
   */
  claude: string;
  codex: string;
  trigger: string;
  /**
   * Override is the user's choice, "" when the skill is as its author
   * made it; AuthorTrigger is then what the author shipped.
   */
  override: string;
  authorTrigger: string;
}

/** State is what the frontend renders from. */
export interface State {
  config: Config;
  skills: Skill[];
  home: string;
}

/**
 * Target is a place skills get installed to: the global skills of a machine
 * or a project directory, on this machine or on an SSH host.
 */
export interface Target {
  id: string;
  name: string;
  /**
   * Host is an SSH destination (e.g. an alias of ~/.ssh/config). Empty
   * means this machine.
   */
  host: string;
  /**
   * Path is the project directory. Unused for global targets, which
   * live in the home directory.
   */
  path: string;
  global: boolean;
  /**
   * Mode is "link" (symlink to the hub's copy) or "copy". Remote targets
   * always copy.
   */
  mode: string;
  /** Agents installs into .agents/skills, Claude into .claude/skills. */
  agents: boolean;
  claude: boolean;
}

/** TargetStatus is the result of scanning a target. */
export interface TargetStatus {
  targetId: string;
  error: string;
  items: Installed[];
}

/**
 * TriggerOverride is the user's choice for a skill, kept in the config so it
 * outlives updates of the skill.
 */
export interface TriggerOverride {
  /** "manual" or "auto" */
  mode: string;
  /**
   * OrigClaude and OrigCodex are what the skill's author shipped, to
   * show and to restore.
   */
  origClaude: string;
  origCodex: string;
}

// ---- Services ----

/** Hub is the service the frontend calls. */
export const Hub = {
  /**
   * AddHost adds the global skills of an SSH host, after checking that the
   * host is reachable.
   */
  addHost(host: string): Promise<Target> {
    return call("Hub.AddHost", host);
  },
  /** AddProject adds a project directory, on this machine when host is empty. */
  addProject(host: string, path: string, name: string): Promise<Target> {
    return call("Hub.AddProject", host, path, name);
  },
  /** AddSource links a local folder of skills. */
  addSource(path: string): Promise<void> {
    return call("Hub.AddSource", path);
  },
  /** Install installs or refreshes the named skills in a target. */
  install(targetID: string, names: string[]): Promise<void> {
    return call("Hub.Install", targetID, names);
  },
  /** OpenPath opens a file or directory of this machine with its default app. */
  openPath(path: string): Promise<void> {
    return call("Hub.OpenPath", path);
  },
  /** PickFolder shows a directory picker and returns the chosen path, or "". */
  pickFolder(): Promise<string> {
    return call("Hub.PickFolder");
  },
  /** ReadSkill returns the SKILL.md of a skill. */
  readSkill(name: string): Promise<string> {
    return call("Hub.ReadSkill", name);
  },
  /** RemoveSource unlinks a local folder. Nothing is deleted. */
  removeSource(id: string): Promise<void> {
    return call("Hub.RemoveSource", id);
  },
  /** RemoveTarget forgets a target. Its installed skills stay on disk. */
  removeTarget(id: string): Promise<void> {
    return call("Hub.RemoveTarget", id);
  },
  /** SSHHosts lists the host aliases of ~/.ssh/config. */
  sshHosts(): Promise<string[]> {
    return call("Hub.SSHHosts");
  },
  /**
   * ScanTarget lists what is installed in a target. Failures, such as an
   * unreachable host, are reported in the status.
   */
  scanTarget(id: string): Promise<TargetStatus> {
    return call("Hub.ScanTarget", id);
  },
  /**
   * SetGroup lists the named skills under group. An empty group restores the
   * default, the package or folder a skill came from.
   */
  setGroup(names: string[], group: string): Promise<void> {
    return call("Hub.SetGroup", names, group);
  },
  /**
   * SetStorePath moves the hub to another store directory. The old one is
   * left as it is.
   */
  setStorePath(path: string): Promise<void> {
    return call("Hub.SetStorePath", path);
  },
  /**
   * SetTrigger makes the named skills manual or auto in both Claude Code and
   * Codex, whatever their sources say now or after an update. An empty mode
   * drops the choice and restores what the author shipped.
   */
  setTrigger(names: string[], mode: string): Promise<void> {
    return call("Hub.SetTrigger", names, mode);
  },
  /** State returns the config and the skills of the store and linked folders. */
  state(): Promise<State> {
    return call("Hub.State");
  },
  /**
   * StoreInstall installs skills into the store. spec is a package for
   * `skills add` (a GitHub repository, a URL…), optionally followed by its
   * flags, or a whole install command. Skills that are new or changed
   * afterwards are listed under group when one is given.
   */
  storeInstall(spec: string, group: string, log: Channel<string>): Promise<void> {
    return call("Hub.StoreInstall", spec, group, log);
  },
  /**
   * StoreRemove deletes the named skills from the store. Copies and links in
   * targets are not touched.
   */
  storeRemove(names: string[], log: Channel<string>): Promise<void> {
    return call("Hub.StoreRemove", names, log);
  },
  /**
   * StoreUpdate updates the named store skills to their latest versions, or
   * all of them when names is empty.
   */
  storeUpdate(names: string[], log: Channel<string>): Promise<void> {
    return call("Hub.StoreUpdate", names, log);
  },
  /** Uninstall removes the named skills from a target. */
  uninstall(targetID: string, names: string[]): Promise<void> {
    return call("Hub.Uninstall", targetID, names);
  },
  /** UpdateTarget changes a target's name, install mode and directories. */
  updateTarget(t: Target): Promise<void> {
    return call("Hub.UpdateTarget", t);
  },
} as const;
